Update 10-supp-addressing-data.Rmd
eigensong/r-novice-inflammation pull request #1
Opened 2020-05-27 22:32 UTC by eigensong

Dear Carpentries Community,

In my instructor training I learnt about "fluid representations" where multiple words for the same concept can confuse learners. I noticed that in the Addressing Data most of the lesson is really careful to avoid fluid representations, by consistently using the word addressing to describe accessing parts of a data frame, rather than mixing in words like subsetting or indexing. However, the titles for the three sections of the types of addressing are:
Addressing by Index
Addressing by Name
Logical Indexing

To fix this issue I suggest replace 'indexing' with 'addressing' across the whole document (as that terminology is only used right at the end) and changing the title 'Logical Indexing' to 'Addressing by Logical Vector'.

Cheers,

Elena

2020-05-27 22:42 UTC, HaoZeke requested changes
Thanks for this, please consider adding a line stating that this particular form of addressing is commonly called "Logical Indexing".

2020-05-27 22:53 UTC, eigensong commented
I've added a sentence. Is that what you had in mind?

2020-05-27 22:54 UTC, HaoZeke approved these changes
Fantastic work. Thanks.

2020-05-27 22:55 UTC, HaoZeke commented
Ah I just realized something. This is a PR which is aimed at your own `master`, please point one at the upstream [repo here](https://github.com/swcarpentry/r-novice-inflammation/compare).

2020-05-27 23:01 UTC, eigensong commented
Right, I see. Is there a way to convert this pull request to one for the upstream repo? Or do I need to start a new pull request on that repo? Sorry, this is a learning exercise for me in using github!

2020-05-27 23:05 UTC, HaoZeke commented
No worries, [apparently it is possible](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request) for you to edit this one to point to the SWC repo.

2020-05-28 01:45 UTC, eigensong commented
Following those instructions, I get a drop down menu, but I can't see how to select the swc version from that list.

![image](https://user-images.githubusercontent.com/42173162/83089023-9d42c400-a0d8-11ea-8f26-99d2d1151a64.png)

2020-05-28 01:57 UTC, HaoZeke commented
o.O Ah I guess it isn't possible then >.<
Please open a new one then?

2020-05-28 02:16 UTC, eigensong commented
OK, thanks for getting back to me. Do I just close this one?

2020-05-28 03:05 UTC, HaoZeke commented
Yup that would be best

2020-05-28 03:43 UTC, closed without merging